# Generated by Django 4.0.2 on 2022-03-09 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thepantry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypantry',
            name='pantry_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pid', to='thepantry.pantrymodel'),
        ),
        migrations.AlterField(
            model_name='mypantry',
            name='pantry_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pname', to='thepantry.pantrymodel'),
        ),
    ]
