# Generated by Django 4.0.2 on 2022-03-09 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thepantry', '0002_mypantry_pantry_name_alter_mypantry_pantry_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypantry',
            name='pantry_name',
        ),
        migrations.AddField(
            model_name='mypantry',
            name='item_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientname', to='thepantry.ingredients'),
        ),
    ]
