# Generated by Django 4.0.2 on 2022-03-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thepantry', '0003_remove_mypantry_pantry_name_mypantry_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypantry',
            name='item_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
