# Generated by Django 4.0.2 on 2022-03-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thepantry', '0005_pantrymodel_slug_alter_mypantry_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantrymodel',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pantrymodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True),
        ),
    ]
