# Generated by Django 4.0.2 on 2022-03-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thepantry', '0006_alter_pantrymodel_name_alter_pantrymodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypantry',
            name='pantry_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mypantry',
            name='slug',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
